@tenantId=019f86b1-6e4b-726b-a97b-4e54ba61ef84

### Tenant Create
POST http://localhost:8080/api/v1/tenants
Content-Type: application/json

{
  "name": "Slow Test"
}

### Endpoint Create
POST http://localhost:8080/api/v1/tenants/{{tenantId}}/endpoints
Content-Type: application/json

{
  "url": "https://httpbin.org/delay/10",
  "eventTypes": ["slow.test"]
}

### Endpoint Get
GET http://localhost:8080/api/v1/tenants/{{tenantId}}/endpoints

### THROW 400
POST http://localhost:8080/api/v1/tenants/{{tenantId}}/endpoints
Content-Type: application/json

{
  "url": "https://acme.com/hook",
  "description": "",
  "eventTypes": []
}

### THROW 404
POST http://localhost:8080/api/v1/tenants/00000000-0000-0000-0000-000000000000/endpoints
Content-Type: application/json

{
  "url": "https://acme.com/hook",
  "description": "Ana webhook",
  "eventTypes": ["payment.succeeded", "order.created"]
}


### Ingest POST
POST http://localhost:8080/api/v1/tenants/{{tenantId}}/events
Content-Type: application/json

{
  "eventType": "slow.test",
  "payload": "{\"x\": 1}"
}