spring:
  application:
    name: ulak
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ulak}
    username: ${DB_USERNAME:ulak}
    password: ${DB_PASSWORD:ulak}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    dev.enes.ulak: info
    org.hibernate.SQL: warn
  pattern:
    level: "%5p [%X{correlationId:-}]"